Repository uPortal-contrib/CardWebComponents, pull requests merged in 2018-12, with the labels that each got.

#39 i18n: add italian support
  README.md
  src/my-card.js
  static/i18n/it/messages.json
Labels: internationalization i18n

#42 messages: fix spellings in en and fr
  static/i18n/en-US/messages.json
  static/i18n/fr-FR/messages.json
Labels: internationalization i18n

#44 feat: adopt sass
  package-lock.json
  package.json
  static/css/my-card.css
  static/scss/my-card.scss
Labels: new feature, style

#46 style: improvements in .scss
  static/css/my-card.css
  static/scss/my-card.scss
Labels: enhancement, style

#47 style: improvement the different states of the menu are visible
  src/my-card.js
  static/css/my-card.css
  static/scss/my-card.scss
Labels: accessibility, bug, new feature, style

#55 i18n + style: fix (verified) messages in arabic + fix action buttons …
  static/css/my-card.css
  static/i18n/ar/messages.json
  static/scss/my-card.scss
Labels: internationalization i18n, style

#57 style: fix the closing menu animation is now smooth
  static/css/my-card.css
  static/scss/my-card.scss
Labels: style

#59 style: minor cleanup
  static/scss/my-card.scss
Labels: style

#62 a11y + i18n: the label of the social menu is internationalized
  src/my-card.js
  static/i18n/ar/messages.json
  static/i18n/en-US/messages.json
  static/i18n/es-ES/messages.json
  static/i18n/fr-FR/messages.json
  static/i18n/it/messages.json
  static/i18n/nl-NL/messages.json
Labels: accessibility, enhancement, internationalization i18n

#74 fix: remove trailing idref
  src/my-card.js
Labels: enhancement

#76 i18n + feat: Add Support for Simplified Chinese zn-CN
  src/my-card.js
  static/i18n/zn-CN/messages.json
  static/index_zn-CN.html
  static/scss/my-card.scss
Labels: enhancement, internationalization i18n, new feature

#78 doc: update uportal-contrib links in readme
  README.md
Labels: Documentation
